-- Built-in prompts for the Assistant plugin
-- DO NOT EDIT THIS FILE - Use configuration.lua or the UI to add custom prompts

return {
    highlight_context = {
        prompts = {
            explain = {
                text = "Explain",
                system_prompt = "You are a helpful assistant that explains complex topics clearly and concisely. Break down concepts in an understandable way.",
                user_prompt = "Please explain the following text: {highlighted_text}",
                include_book_context = true
            },
            eli5 = {
                text = "ELI5",
                system_prompt = "You are a helpful assistant that explains complex topics clearly and concisely. Break down concepts into ELI5 terms.",
                user_prompt = "Please ELI5 the following text: {highlighted_text}",
                include_book_context = false
            },
            summarize = {
                text = "Summarize",
                system_prompt = "You are a helpful assistant. Provide clear, concise summaries that capture the main points.",
                user_prompt = "Please provide a concise summary of the following text: {highlighted_text}",
                include_book_context = true
            }
        }
    },
    -- Book context prompts (when asking about a book via file browser or "chat about book" gesture)
    book_context = {
        prompts = {
            book_info = {
                text = "Book Info",
                user_prompt = [[Tell me about the book "{title}"{author_clause}. Include information about:
- What the book is about
- Its significance and impact  
- Why someone might want to read it
- Any interesting facts about it

Please be concise but informative.]]
            },
            similar_books = {
                text = "Find Similar",
                user_prompt = [[Based on the book "{title}"{author_clause}, recommend 5-7 similar books that readers might enjoy. For each recommendation, briefly explain why it's similar or why the reader might like it.]]
            },
            explain_author = {
                text = "About Author",
                user_prompt = [[Tell me about the author of "{title}"{author_clause}. Include:
- Brief biography
- Their major works and contributions
- Writing style and themes
- Historical/cultural context of their work]],
                requires = "author"
            },
            historical_context = {
                text = "Historical Context", 
                user_prompt = [[Provide historical context for "{title}"{author_clause}:
- When was it written and what was happening at that time
- Historical events or movements that influenced the work
- How the book reflects or responds to its historical moment
- Its historical significance or impact]]
            }
        }
    },
    -- Multi-book context prompts (when comparing multiple selected books)
    multi_book_context = {
        prompts = {
            compare_books = {
                text = "Compare Books",
                user_prompt = [[Compare and contrast these {count} books:

{books_list}

Please analyze:
- Common themes or topics
- Key differences in approach or perspective
- Target audiences
- Writing styles (if authors are known)
- Which readers might prefer which book and why

Be concise but insightful.]]
            },
            common_themes = {
                text = "Find Common Themes",
                user_prompt = [[Looking at these {count} books:

{books_list}

What common themes, topics, or patterns can you identify across this selection? Consider:
- Subject matter overlap
- Shared historical contexts
- Similar literary techniques or genres
- Common target audiences or purposes]]
            },
            collection_summary = {
                text = "Analyze Collection",
                user_prompt = [[Analyze this collection of {count} books:

{books_list}

Provide insights about:
- What kind of reader would have this collection
- What the selection reveals about their interests
- Any notable gaps or missing perspectives
- Recommendations for what to add next]]
            },
            quick_summaries = {
                text = "Quick Summaries",
                user_prompt = [[For each of these {count} books, provide a 2-3 sentence summary:

{books_list}

Focus on the main premise and why someone might want to read it.]]
            }
        }
    }
}